In [1]:
import pandas as pd

In [2]:
pd.__file__

'/workspaces/docker-workshop-DE/pipeline/.venv/lib/python3.13/site-packages/pandas/__init__.py'

In [3]:
prefix= 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'

url= f'{prefix}/yellow_tripdata_2021-01.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz'

In [4]:
df=pd.read_csv(url)

/tmp/ipykernel_27966/773934961.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(url)

In [5]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,NaN,2021-01-25 08:32:04,2021-01-25 08:49:32,NaN,8.80,NaN,NaN,135,82,NaN,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,NaN,2021-01-25 08:34:00,2021-01-25 09:04:00,NaN,5.86,NaN,NaN,42,161,NaN,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,NaN,2021-01-25 08:37:00,2021-01-25 08:53:00,NaN,4.45,NaN,NaN,14,106,NaN,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,NaN,2021-01-25 08:28:00,2021-01-25 08:50:00,NaN,10.04,NaN,NaN,175,216,NaN,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,NaN,2021-01-25 08:38:00,2021-01-25 08:50:00,NaN,4.93,NaN,NaN,248,168,NaN,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [6]:
url2= 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet'

In [7]:
url2

'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet'

In [8]:
df2 = pd.read_parquet(url2)

In [13]:
df2

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.00,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.00
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.10,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.00
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.10,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.00
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.20,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.00
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.80,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3475221,2,2025-01-31 23:01:48,2025-01-31 23:16:29,NaN,3.35,NaN,None,79,237,0,15.85,0.0,0.5,0.00,0.0,1.0,20.60,NaN,NaN,0.75
3475222,2,2025-01-31 23:50:29,2025-02-01 00:17:27,NaN,8.73,NaN,None,161,116,0,28.14,0.0,0.5,0.00,0.0,1.0,32.89,NaN,NaN,0.75
3475223,2,2025-01-31 23:26:59,2025-01-31 23:43:01,NaN,2.64,NaN,None,144,246,0,14.91,0.0,0.5,0.00,0.0,1.0,19.66,NaN,NaN,0.75
3475224,2,2025-01-31 23:14:34,2025-01-31 23:34:52,NaN,3.16,NaN,None,142,107,0,17.55,0.0,0.5,0.00,0.0,1.0,22.30,NaN,NaN,0.75
3475225,2,2025-01-31 23:56:42,2025-02-01 00:07:27,NaN,2.29,NaN,None,237,238,0,12.09,0.0,0.5,0.00,0.0,1.0,16.09,NaN,NaN,0.00

In [9]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [15]:
df2.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [10]:
len(df)

1369765

In [11]:
len(df2)

3475226

In [12]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [13]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,<NA>,2021-01-25 08:32:04,2021-01-25 08:49:32,<NA>,8.80,<NA>,<NA>,135,82,<NA>,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,<NA>,2021-01-25 08:34:00,2021-01-25 09:04:00,<NA>,5.86,<NA>,<NA>,42,161,<NA>,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,<NA>,2021-01-25 08:37:00,2021-01-25 08:53:00,<NA>,4.45,<NA>,<NA>,14,106,<NA>,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,<NA>,2021-01-25 08:28:00,2021-01-25 08:50:00,<NA>,10.04,<NA>,<NA>,175,216,<NA>,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,<NA>,2021-01-25 08:38:00,2021-01-25 08:50:00,<NA>,4.93,<NA>,<NA>,248,168,<NA>,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [24]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [14]:
df['tpep_pickup_datetime]

SyntaxError: unterminated string literal (detected at line 1) (3630759405.py, line 1)

In [15]:
df[tpep_pickup_datetime]

NameError: name 'tpep_pickup_datetime' is not defined

In [16]:
df['tpep_pickup_datetime']

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369760   2021-01-25 08:32:04
1369761   2021-01-25 08:34:00
1369762   2021-01-25 08:37:00
1369763   2021-01-25 08:28:00
1369764   2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: datetime64[ns]

In [17]:
!uv add sqlalchemy

Resolved 119 packages in 0.60ms
Audited 11 packages in 0.18ms

In [18]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [19]:
!uv add psycopg2-binary

Resolved 119 packages in 0.57ms
Audited 11 packages in 0.18ms

In [21]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [22]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [23]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,<NA>,2021-01-25 08:32:04,2021-01-25 08:49:32,<NA>,8.80,<NA>,<NA>,135,82,<NA>,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,<NA>,2021-01-25 08:34:00,2021-01-25 09:04:00,<NA>,5.86,<NA>,<NA>,42,161,<NA>,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,<NA>,2021-01-25 08:37:00,2021-01-25 08:53:00,<NA>,4.45,<NA>,<NA>,14,106,<NA>,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,<NA>,2021-01-25 08:28:00,2021-01-25 08:50:00,<NA>,10.04,<NA>,<NA>,175,216,<NA>,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,<NA>,2021-01-25 08:38:00,2021-01-25 08:50:00,<NA>,4.93,<NA>,<NA>,248,168,<NA>,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [36]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [51]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [26]:
df=next(df_iter)

In [27]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-04 14:04:31,2021-01-04 14:08:52,3,0.70,1,N,234,224,2,5.0,2.5,0.5,0.00,0.0,0.3,8.30,2.5
99996,1,2021-01-04 14:18:46,2021-01-04 14:35:45,2,3.30,1,N,234,236,1,14.5,2.5,0.5,3.55,0.0,0.3,21.35,2.5
99997,1,2021-01-04 14:42:41,2021-01-04 14:59:22,2,4.70,1,N,236,79,1,17.0,2.5,0.5,4.05,0.0,0.3,24.35,2.5
99998,2,2021-01-04 14:39:02,2021-01-04 15:09:37,2,17.95,2,N,132,148,1,52.0,0.0,0.5,5.00,0.0,0.3,60.30,2.5
99999,2,2021-01-04 14:49:36,2021-01-04 14:54:44,5,0.37,1,N,236,236,2,5.0,0.0,0.5,0.00,0.0,0.3,8.30,2.5

In [28]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,2021-01-04 14:04:31,2021-01-04 14:08:52,3,0.70,1,N,234,224,2,5.0,2.5,0.5,0.00,0.0,0.3,8.30,2.5
99996,1,2021-01-04 14:18:46,2021-01-04 14:35:45,2,3.30,1,N,234,236,1,14.5,2.5,0.5,3.55,0.0,0.3,21.35,2.5
99997,1,2021-01-04 14:42:41,2021-01-04 14:59:22,2,4.70,1,N,236,79,1,17.0,2.5,0.5,4.05,0.0,0.3,24.35,2.5
99998,2,2021-01-04 14:39:02,2021-01-04 15:09:37,2,17.95,2,N,132,148,1,52.0,0.0,0.5,5.00,0.0,0.3,60.30,2.5
99999,2,2021-01-04 14:49:36,2021-01-04 14:54:44,5,0.37,1,N,236,236,2,5.0,0.0,0.5,0.00,0.0,0.3,8.30,2.5

In [40]:
df=next(df_iter)

In [41]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
500000,1,2021-01-13 20:39:01,2021-01-13 20:45:33,0,1.00,1,Y,68,107,1,6.5,3.0,0.5,2.55,0.0,0.3,12.85,2.5
500001,1,2021-01-13 20:53:14,2021-01-13 21:08:14,0,5.70,1,N,107,13,1,18.5,3.0,0.5,4.45,0.0,0.3,26.75,2.5
500002,1,2021-01-13 20:15:39,2021-01-13 20:19:42,2,0.90,1,N,237,162,1,5.5,3.0,0.5,2.00,0.0,0.3,11.30,2.5
500003,1,2021-01-13 20:30:14,2021-01-13 20:33:51,1,1.40,1,N,233,141,1,6.0,3.0,0.5,1.95,0.0,0.3,11.75,2.5
500004,2,2021-01-13 19:52:44,2021-01-13 19:56:19,1,1.46,1,N,233,141,1,6.0,0.5,0.5,1.96,0.0,0.3,11.76,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,2,2021-01-15 22:45:13,2021-01-15 22:48:21,1,0.84,1,N,164,234,2,5.0,0.5,0.5,0.00,0.0,0.3,8.80,2.5
599996,2,2021-01-15 22:50:31,2021-01-15 22:51:10,1,0.33,1,N,90,90,2,3.0,0.5,0.5,0.00,0.0,0.3,6.80,2.5
599997,2,2021-01-15 22:52:14,2021-01-15 23:11:11,1,5.20,1,N,249,49,2,18.0,0.5,0.5,0.00,0.0,0.3,21.80,2.5
599998,1,2021-01-15 22:43:41,2021-01-15 22:58:55,1,3.50,1,N,237,226,1,14.0,3.0,0.5,5.30,0.0,0.3,23.10,2.5
599999,1,2021-01-15 22:23:04,2021-01-15 22:45:59,1,4.60,1,N,142,116,2,18.5,3.0,0.5,0.00,0.0,0.3,22.30,2.5

In [32]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
100000,2,2021-01-04 14:42:51,2021-01-04 14:51:18,1,1.43,1,N,170,161,2,7.5,0.0,0.5,0.00,0.0,0.3,10.80,2.5
100001,2,2021-01-04 14:04:39,2021-01-04 14:18:41,1,2.82,1,N,170,143,2,12.0,0.0,0.5,0.00,0.0,0.3,15.30,2.5
100002,1,2021-01-04 14:12:49,2021-01-04 14:31:21,0,2.70,1,N,68,239,1,13.5,2.5,0.5,3.35,0.0,0.3,20.15,2.5
100003,1,2021-01-04 14:43:55,2021-01-04 14:48:45,1,0.70,1,N,246,68,2,5.5,2.5,0.5,0.00,0.0,0.3,8.80,2.5
100004,1,2021-01-04 14:59:16,2021-01-04 15:07:08,1,1.60,1,N,161,234,1,8.0,2.5,0.5,2.25,0.0,0.3,13.55,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1,2021-01-06 17:02:39,2021-01-06 17:09:21,2,1.10,1,N,236,237,1,6.5,3.5,0.5,3.20,0.0,0.3,14.00,2.5
199996,1,2021-01-06 17:12:00,2021-01-06 17:17:55,1,1.60,1,N,237,239,1,7.0,3.5,0.5,2.25,0.0,0.3,13.55,2.5
199997,2,2021-01-06 17:03:41,2021-01-06 17:07:37,2,1.06,1,N,161,186,1,5.5,1.0,0.5,1.96,0.0,0.3,11.76,2.5
199998,2,2021-01-06 17:14:11,2021-01-06 17:29:58,2,5.24,1,N,68,238,1,18.0,1.0,0.5,1.00,0.0,0.3,23.30,2.5
199999,2,2021-01-06 17:45:43,2021-01-06 17:52:37,2,1.49,1,N,68,114,1,7.0,1.0,0.5,1.50,0.0,0.3,12.80,2.5

In [33]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
100000,2,2021-01-04 14:42:51,2021-01-04 14:51:18,1,1.43,1,N,170,161,2,7.5,0.0,0.5,0.00,0.0,0.3,10.80,2.5
100001,2,2021-01-04 14:04:39,2021-01-04 14:18:41,1,2.82,1,N,170,143,2,12.0,0.0,0.5,0.00,0.0,0.3,15.30,2.5
100002,1,2021-01-04 14:12:49,2021-01-04 14:31:21,0,2.70,1,N,68,239,1,13.5,2.5,0.5,3.35,0.0,0.3,20.15,2.5
100003,1,2021-01-04 14:43:55,2021-01-04 14:48:45,1,0.70,1,N,246,68,2,5.5,2.5,0.5,0.00,0.0,0.3,8.80,2.5
100004,1,2021-01-04 14:59:16,2021-01-04 15:07:08,1,1.60,1,N,161,234,1,8.0,2.5,0.5,2.25,0.0,0.3,13.55,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1,2021-01-06 17:02:39,2021-01-06 17:09:21,2,1.10,1,N,236,237,1,6.5,3.5,0.5,3.20,0.0,0.3,14.00,2.5
199996,1,2021-01-06 17:12:00,2021-01-06 17:17:55,1,1.60,1,N,237,239,1,7.0,3.5,0.5,2.25,0.0,0.3,13.55,2.5
199997,2,2021-01-06 17:03:41,2021-01-06 17:07:37,2,1.06,1,N,161,186,1,5.5,1.0,0.5,1.96,0.0,0.3,11.76,2.5
199998,2,2021-01-06 17:14:11,2021-01-06 17:29:58,2,5.24,1,N,68,238,1,18.0,1.0,0.5,1.00,0.0,0.3,23.30,2.5
199999,2,2021-01-06 17:45:43,2021-01-06 17:52:37,2,1.49,1,N,68,114,1,7.0,1.0,0.5,1.50,0.0,0.3,12.80,2.5

In [49]:
!uv add tqdm

Resolved 120 packages in 0.58ms
Audited 12 packages in 0.20ms

In [45]:
from tqdm.auto import tqdm

In [52]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]